### ISSUE TITLE
Pinboard API Token Issues

### ISSUE THREAD

**Issue by cooperpellaton** [patrickleweryharris/pintools#1]
## Problem

Running with ENV VAR `PINBOARD_API_TOKEN` returns a [500](https://github.com/lionheart/pinboard.py/blob/b70bde28d903201e6ec831de8b8e4462ccc31dc8/bin/pinboard#L76), thus the var wasn't sourced. Running with positional succeeds.

## General Feedback 

- Positional only works _immediately_ after `pintools`. Placing anywhere else fails: 
    - `pintools --pinboard_token` ✅ , 
    - but `pintools ... --pinboard_token` ❌ . 
- Missing [`pyyaml`](https://pyyaml.org/) dependency on a fresh install.

**Comment by cooperpellaton** [comment]
IFTT link in [README](https://github.com/patrickleweryharris/pintools/blob/master/README.md#L67) fails to resolve.

**Comment by patrickleweryharris** [comment]
I'm not observing the problem with `PINBOARD_API_TOKEN` returning a 500. Behavior should be the same for command line arg / env var, as the env var is set as the default for the command line argument. Just did a fresh install on a VM, and was able to get this working through providing just the environment variable. 

Issue with the order for `--pinboard_token` is an artifact of how the `argparse` modules handles subcommands. I've added a clarifying comment in the help dialog in 9d8e9955b9aa3081933651fa8810485fdeb01d61 which has been released to pypi as v1.0.3

PyYAML has been added to the requirements and the link in the README fixed as well. Was able to get it working without the PyYAML dependency, but this may be due to my package manager installing dev libraries when I installed Python.
